name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - .github/workflows/dockerhub-description.yml
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - .github/workflows/dockerhub-description.yml
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-bases:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
            tag-suffix: amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64,linux/arm/v7
            tag-suffix: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Extract Version
        id: get_version
        run: |
          VERSION=$(grep "ARG IPERF3_VERSION=" Dockerfile | cut -d'=' -f2 | tr -d '[:space:]')
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and load (AMD64 only)
        if: matrix.platform == 'linux/amd64'
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          platforms: linux/amd64
          tags: local-test:latest
          cache-from: type=gha,scope=${{ matrix.tag-suffix }}
          cache-to: type=gha,mode=max,scope=${{ matrix.tag-suffix }}

      - name: Run Trivy scanner
        if: matrix.platform == 'linux/amd64'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'local-test:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results
        if: always() && matrix.platform == 'linux/amd64'
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Check Trivy Break Build
        if: matrix.platform == 'linux/amd64'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'local-test:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build and Push by Digest
        id: build
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          provenance: mode=max
          sbom: true
          outputs: type=image,name=${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha,scope=${{ matrix.tag-suffix }}
          cache-to: type=gha,mode=max,scope=${{ matrix.tag-suffix }}

      - name: Export Digest
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
          echo "Output Digest: $digest"

      - name: Upload Digest
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v6
        with:
          name: digests-${{ matrix.tag-suffix }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-tags:
    needs: build-bases
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.1

      - name: Extract Version
        run: |
          VERSION=$(grep "ARG IPERF3_VERSION=" Dockerfile | cut -d'=' -f2 | tr -d '[:space:]')
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download Digests
        uses: actions/download-artifact@v7
        with:
          pattern: digests-*
          path: /tmp/digests
          merge-multiple: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Manifest and Push
        id: manifest
        run: |
          DIGESTS=$(printf '${{ env.IMAGE_NAME }}@sha256:%s ' $(ls /tmp/digests))
          
          TAG_LATEST="${{ env.IMAGE_NAME }}:latest"
          TAG_VER="${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}"
          TAG_FULL="${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}-${GITHUB_SHA::7}"
          
          docker buildx imagetools create -t $TAG_LATEST -t $TAG_VER -t $TAG_FULL $DIGESTS
          
          FINAL_DIGEST=$(docker buildx imagetools inspect $TAG_LATEST | grep "^Digest:" | awk '{print $2}')
          
          echo "Captured Digest: $FINAL_DIGEST"
          echo "FINAL_DIGEST=$FINAL_DIGEST" >> $GITHUB_ENV

      - name: Sign the published Docker image
        run: |
          echo "Signing image: ${{ env.IMAGE_NAME }}@${{ env.FINAL_DIGEST }}"
          cosign sign --yes --recursive "${{ env.IMAGE_NAME }}@${{ env.FINAL_DIGEST }}"
